//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by tag-const-gen. DO NOT EDIT.

package main

import "fmt"

const (
	// InventoryDesiredComposedXbucketsPrefix name generated from tag 'desired-composed' of field 'Inventory.DesiredBuckets'.
	InventoryDesiredComposedXbucketsPrefix = "xbuckets-"
)

// InventoryDesiredComposedXbuckets convenience function to generate prefixed names
func InventoryDesiredComposedXbuckets(name string) string {
	return fmt.Sprintf("xbuckets-%s", name)
}
