// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.5.0-rc.0.0.20260814234830-5bace94891a5 DO NOT EDIT.
package v1alpha1

import (
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ClusterNopResourceAPIVersion.
const (
	ClusterNopResourceAPIVersionNopCrossplaneIoV1Alpha1 ClusterNopResourceAPIVersion = "nop.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceAPIVersion enum.
func (e ClusterNopResourceAPIVersion) Valid() bool {
	switch e {
	case ClusterNopResourceAPIVersionNopCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNopResourceKind.
const (
	ClusterNopResourceKindClusterNopResource ClusterNopResourceKind = "ClusterNopResource"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceKind enum.
func (e ClusterNopResourceKind) Valid() bool {
	switch e {
	case ClusterNopResourceKindClusterNopResource:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNopResourceSpecDeletionPolicy.
const (
	ClusterNopResourceSpecDeletionPolicyDelete ClusterNopResourceSpecDeletionPolicy = "Delete"
	ClusterNopResourceSpecDeletionPolicyOrphan ClusterNopResourceSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceSpecDeletionPolicy enum.
func (e ClusterNopResourceSpecDeletionPolicy) Valid() bool {
	switch e {
	case ClusterNopResourceSpecDeletionPolicyDelete:
		return true
	case ClusterNopResourceSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNopResourceSpecManagementPoliciesItem.
const (
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItem               ClusterNopResourceSpecManagementPoliciesItem = "*"
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemCreate         ClusterNopResourceSpecManagementPoliciesItem = "Create"
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemDelete         ClusterNopResourceSpecManagementPoliciesItem = "Delete"
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemLateInitialize ClusterNopResourceSpecManagementPoliciesItem = "LateInitialize"
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemObserve        ClusterNopResourceSpecManagementPoliciesItem = "Observe"
	ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemUpdate         ClusterNopResourceSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceSpecManagementPoliciesItem enum.
func (e ClusterNopResourceSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItem:
		return true
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemCreate:
		return true
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemDelete:
		return true
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemLateInitialize:
		return true
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemObserve:
		return true
	case ClusterNopResourceSpecManagementPoliciesItemClusterNopResourceSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNopResourceSpecProviderConfigRefPolicyResolution.
const (
	ClusterNopResourceSpecProviderConfigRefPolicyResolutionOptional ClusterNopResourceSpecProviderConfigRefPolicyResolution = "Optional"
	ClusterNopResourceSpecProviderConfigRefPolicyResolutionRequired ClusterNopResourceSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceSpecProviderConfigRefPolicyResolution enum.
func (e ClusterNopResourceSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case ClusterNopResourceSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case ClusterNopResourceSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ClusterNopResourceSpecProviderConfigRefPolicyResolve.
const (
	ClusterNopResourceSpecProviderConfigRefPolicyResolveAlways       ClusterNopResourceSpecProviderConfigRefPolicyResolve = "Always"
	ClusterNopResourceSpecProviderConfigRefPolicyResolveIfNotPresent ClusterNopResourceSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ClusterNopResourceSpecProviderConfigRefPolicyResolve enum.
func (e ClusterNopResourceSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case ClusterNopResourceSpecProviderConfigRefPolicyResolveAlways:
		return true
	case ClusterNopResourceSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoCrossplaneNopV1Alpha1ClusterNopResource A ClusterNopResource is an example API type.
type IoCrossplaneNopV1Alpha1ClusterNopResource = ClusterNopResource

// ClusterNopResourceAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ClusterNopResourceAPIVersion string

// ClusterNopResourceKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ClusterNopResourceKind string

// ClusterNopResourceSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type ClusterNopResourceSpecDeletionPolicy string

// ClusterNopResourceSpecForProviderConditionAfterItem ConditionAfter specifies a condition of a NopResource that should be
// set after a certain duration.
type ClusterNopResourceSpecForProviderConditionAfterItem struct {
	// ConditionReason ConditionReason to set - e.g. Available.
	ConditionReason *string `json:"conditionReason,omitempty"`

	// ConditionStatus ConditionStatus to set - e.g. True.
	ConditionStatus *string `json:"conditionStatus,omitempty"`

	// ConditionType ConditionType to set - e.g. Ready.
	ConditionType *string `json:"conditionType,omitempty"`

	// Time Time is the duration after which the condition should be set.
	Time *string `json:"time,omitempty"`
}

// ClusterNopResourceSpecForProviderConnectionDetailsItem ConnectionDetail specifies a connection detail a NopResource should
// emit.
type ClusterNopResourceSpecForProviderConnectionDetailsItem struct {
	// Name Name of the connection detail.
	Name *string `json:"name,omitempty"`

	// Value Value of the connection detail.
	Value *string `json:"value,omitempty"`
}

// ClusterNopResourceSpecForProviderFields Fields is an arbitrary object you can patch to and from. It has no
// schema, is not validated, and is not used by the NopResource controller.
type ClusterNopResourceSpecForProviderFields = map[string]interface{}

// ClusterNopResourceSpecForProvider NopParameters are the configurable fields of a NopResource.
type ClusterNopResourceSpecForProvider struct {
	// ConditionAfter ConditionAfter can be used to set status conditions after a specified
	// time. By default, a NopResource will only have a status condition of
	// Type: Synced. It will never have a status condition of Type: Ready
	// unless one is configured here.
	ConditionAfter *[]ClusterNopResourceSpecForProviderConditionAfterItem `json:"conditionAfter,omitempty"`

	// ConnectionDetails ConnectionDetails that this NopResource should emit on each reconcile.
	ConnectionDetails *[]ClusterNopResourceSpecForProviderConnectionDetailsItem `json:"connectionDetails,omitempty"`

	// Fields Fields is an arbitrary object you can patch to and from. It has no
	// schema, is not validated, and is not used by the NopResource controller.
	Fields *ClusterNopResourceSpecForProviderFields `json:"fields,omitempty"`
}

// ClusterNopResourceSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type ClusterNopResourceSpecManagementPoliciesItem string

// ClusterNopResourceSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ClusterNopResourceSpecProviderConfigRefPolicyResolution string

// ClusterNopResourceSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ClusterNopResourceSpecProviderConfigRefPolicyResolve string

// ClusterNopResourceSpecProviderConfigRefPolicy Policies for referencing.
type ClusterNopResourceSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ClusterNopResourceSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ClusterNopResourceSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// ClusterNopResourceSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ClusterNopResourceSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ClusterNopResourceSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// ClusterNopResourceSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type ClusterNopResourceSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ClusterNopResourceSpec A NopSpec defines the desired state of a NopResource.
type ClusterNopResourceSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *ClusterNopResourceSpecDeletionPolicy `json:"deletionPolicy,omitempty"`

	// ForProvider NopParameters are the configurable fields of a NopResource.
	ForProvider *ClusterNopResourceSpecForProvider `json:"forProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]ClusterNopResourceSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ClusterNopResourceSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *ClusterNopResourceSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ClusterNopResourceStatusAtProviderFields Fields is an arbitrary object you can patch to and from. It has no
// schema, is not validated, and is not used by the NopResource controller.
type ClusterNopResourceStatusAtProviderFields = map[string]interface{}

// ClusterNopResourceStatusAtProvider NopObservation are the observable fields of a NopResource.
type ClusterNopResourceStatusAtProvider struct {
	// Fields Fields is an arbitrary object you can patch to and from. It has no
	// schema, is not validated, and is not used by the NopResource controller.
	Fields *ClusterNopResourceStatusAtProviderFields `json:"fields,omitempty"`
}

// ClusterNopResourceStatusConditionsItem A Condition that may apply to a resource.
type ClusterNopResourceStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ClusterNopResourceStatus A NopStatus represents the observed state of a NopResource.
type ClusterNopResourceStatus struct {
	// AtProvider NopObservation are the observable fields of a NopResource.
	AtProvider *ClusterNopResourceStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ClusterNopResourceStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// ClusterNopResource A ClusterNopResource is an example API type.
type ClusterNopResource struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ClusterNopResourceAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ClusterNopResourceKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A NopSpec defines the desired state of a NopResource.
	Spec *ClusterNopResourceSpec `json:"spec,omitempty"`

	// Status A NopStatus represents the observed state of a NopResource.
	Status *ClusterNopResourceStatus `json:"status,omitempty"`
}

// IoCrossplaneNopV1Alpha1ClusterNopResourceList ClusterNopResourceList is a list of ClusterNopResource
type IoCrossplaneNopV1Alpha1ClusterNopResourceList = ClusterNopResourceList

// ClusterNopResourceList ClusterNopResourceList is a list of ClusterNopResource
type ClusterNopResourceList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of clusternopresources. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneNopV1Alpha1ClusterNopResource `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecForProviderConditionAfterItem) DeepCopyInto(out *ClusterNopResourceSpecForProviderConditionAfterItem) {
	*out = *in
	if in.ConditionReason != nil {
		in, out := &in.ConditionReason, &out.ConditionReason
		*out = new(string)
		**out = **in
	}
	if in.ConditionStatus != nil {
		in, out := &in.ConditionStatus, &out.ConditionStatus
		*out = new(string)
		**out = **in
	}
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecForProviderConditionAfterItem) DeepCopy() *ClusterNopResourceSpecForProviderConditionAfterItem {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecForProviderConditionAfterItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecForProviderConnectionDetailsItem) DeepCopyInto(out *ClusterNopResourceSpecForProviderConnectionDetailsItem) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecForProviderConnectionDetailsItem) DeepCopy() *ClusterNopResourceSpecForProviderConnectionDetailsItem {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecForProviderConnectionDetailsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecForProvider) DeepCopyInto(out *ClusterNopResourceSpecForProvider) {
	*out = *in
	if in.ConditionAfter != nil {
		in, out := &in.ConditionAfter, &out.ConditionAfter
		*out = new([]ClusterNopResourceSpecForProviderConditionAfterItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]ClusterNopResourceSpecForProviderConditionAfterItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ConnectionDetails != nil {
		in, out := &in.ConnectionDetails, &out.ConnectionDetails
		*out = new([]ClusterNopResourceSpecForProviderConnectionDetailsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]ClusterNopResourceSpecForProviderConnectionDetailsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = new(ClusterNopResourceSpecForProviderFields)
		if *in != nil {
			in, out := *in, *out
			*out = make(ClusterNopResourceSpecForProviderFields, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecForProvider) DeepCopy() *ClusterNopResourceSpecForProvider {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecProviderConfigRefPolicy) DeepCopyInto(out *ClusterNopResourceSpecProviderConfigRefPolicy) {
	*out = *in
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(ClusterNopResourceSpecProviderConfigRefPolicyResolution)
		**out = **in
	}
	if in.Resolve != nil {
		in, out := &in.Resolve, &out.Resolve
		*out = new(ClusterNopResourceSpecProviderConfigRefPolicyResolve)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecProviderConfigRefPolicy) DeepCopy() *ClusterNopResourceSpecProviderConfigRefPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecProviderConfigRefPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecProviderConfigRef) DeepCopyInto(out *ClusterNopResourceSpecProviderConfigRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(ClusterNopResourceSpecProviderConfigRefPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecProviderConfigRef) DeepCopy() *ClusterNopResourceSpecProviderConfigRef {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecProviderConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpecWriteConnectionSecretToRef) DeepCopyInto(out *ClusterNopResourceSpecWriteConnectionSecretToRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpecWriteConnectionSecretToRef) DeepCopy() *ClusterNopResourceSpecWriteConnectionSecretToRef {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpecWriteConnectionSecretToRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceSpec) DeepCopyInto(out *ClusterNopResourceSpec) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(ClusterNopResourceSpecDeletionPolicy)
		**out = **in
	}
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(ClusterNopResourceSpecForProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = new([]ClusterNopResourceSpecManagementPoliciesItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]ClusterNopResourceSpecManagementPoliciesItem, len(*in))
			copy(*out, *in)
		}
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(ClusterNopResourceSpecProviderConfigRef)
		(*in).DeepCopyInto(*out)
	}
	if in.WriteConnectionSecretToRef != nil {
		in, out := &in.WriteConnectionSecretToRef, &out.WriteConnectionSecretToRef
		*out = new(ClusterNopResourceSpecWriteConnectionSecretToRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceSpec) DeepCopy() *ClusterNopResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceStatusAtProvider) DeepCopyInto(out *ClusterNopResourceStatusAtProvider) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = new(ClusterNopResourceStatusAtProviderFields)
		if *in != nil {
			in, out := *in, *out
			*out = make(ClusterNopResourceStatusAtProviderFields, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceStatusAtProvider) DeepCopy() *ClusterNopResourceStatusAtProvider {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceStatusAtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceStatusConditionsItem) DeepCopyInto(out *ClusterNopResourceStatusConditionsItem) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(time.Time)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceStatusConditionsItem) DeepCopy() *ClusterNopResourceStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceStatus) DeepCopyInto(out *ClusterNopResourceStatus) {
	*out = *in
	if in.AtProvider != nil {
		in, out := &in.AtProvider, &out.AtProvider
		*out = new(ClusterNopResourceStatusAtProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]ClusterNopResourceStatusConditionsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]ClusterNopResourceStatusConditionsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceStatus) DeepCopy() *ClusterNopResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResource) DeepCopyInto(out *ClusterNopResource) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(ClusterNopResourceAPIVersion)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(ClusterNopResourceKind)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ClusterNopResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ClusterNopResourceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResource) DeepCopy() *ClusterNopResource {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *ClusterNopResource) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *ClusterNopResource) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *ClusterNopResource) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *ClusterNopResource) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := ClusterNopResourceAPIVersion(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := ClusterNopResourceKind(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &ClusterNopResource{})
		return nil
	})
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterNopResourceList) DeepCopyInto(out *ClusterNopResourceList) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new([]IoCrossplaneNopV1Alpha1ClusterNopResource)
		if *in != nil {
			in, out := *in, *out
			*out = make([]IoCrossplaneNopV1Alpha1ClusterNopResource, len(*in))
			copy(*out, *in)
		}
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ListMeta)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ClusterNopResourceList) DeepCopy() *ClusterNopResourceList {
	if in == nil {
		return nil
	}
	out := new(ClusterNopResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *ClusterNopResourceList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *ClusterNopResourceList) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *ClusterNopResourceList) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *ClusterNopResourceList) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := string(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := string(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &ClusterNopResourceList{})
		return nil
	})
}

// GetConditionReason returns the ConditionReason field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) GetConditionReason() *string {
	if o == nil {
		return nil
	}
	return o.ConditionReason
}

// SetConditionReason sets the ConditionReason field.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) SetConditionReason(v *string) {
	o.ConditionReason = v
}

// GetConditionStatus returns the ConditionStatus field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) GetConditionStatus() *string {
	if o == nil {
		return nil
	}
	return o.ConditionStatus
}

// SetConditionStatus sets the ConditionStatus field.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) SetConditionStatus(v *string) {
	o.ConditionStatus = v
}

// GetConditionType returns the ConditionType field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) GetConditionType() *string {
	if o == nil {
		return nil
	}
	return o.ConditionType
}

// SetConditionType sets the ConditionType field.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) SetConditionType(v *string) {
	o.ConditionType = v
}

// GetTime returns the Time field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) GetTime() *string {
	if o == nil {
		return nil
	}
	return o.Time
}

// SetTime sets the Time field.
func (o *ClusterNopResourceSpecForProviderConditionAfterItem) SetTime(v *string) {
	o.Time = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConnectionDetailsItem) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *ClusterNopResourceSpecForProviderConnectionDetailsItem) SetName(v *string) {
	o.Name = v
}

// GetValue returns the Value field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProviderConnectionDetailsItem) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// SetValue sets the Value field.
func (o *ClusterNopResourceSpecForProviderConnectionDetailsItem) SetValue(v *string) {
	o.Value = v
}

// GetConditionAfter returns the ConditionAfter field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProvider) GetConditionAfter() *[]ClusterNopResourceSpecForProviderConditionAfterItem {
	if o == nil {
		return nil
	}
	return o.ConditionAfter
}

// SetConditionAfter sets the ConditionAfter field.
func (o *ClusterNopResourceSpecForProvider) SetConditionAfter(v *[]ClusterNopResourceSpecForProviderConditionAfterItem) {
	o.ConditionAfter = v
}

// GetConnectionDetails returns the ConnectionDetails field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProvider) GetConnectionDetails() *[]ClusterNopResourceSpecForProviderConnectionDetailsItem {
	if o == nil {
		return nil
	}
	return o.ConnectionDetails
}

// SetConnectionDetails sets the ConnectionDetails field.
func (o *ClusterNopResourceSpecForProvider) SetConnectionDetails(v *[]ClusterNopResourceSpecForProviderConnectionDetailsItem) {
	o.ConnectionDetails = v
}

// GetFields returns the Fields field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecForProvider) GetFields() *ClusterNopResourceSpecForProviderFields {
	if o == nil {
		return nil
	}
	return o.Fields
}

// SetFields sets the Fields field.
func (o *ClusterNopResourceSpecForProvider) SetFields(v *ClusterNopResourceSpecForProviderFields) {
	o.Fields = v
}

// GetResolution returns the Resolution field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecProviderConfigRefPolicy) GetResolution() *ClusterNopResourceSpecProviderConfigRefPolicyResolution {
	if o == nil {
		return nil
	}
	return o.Resolution
}

// SetResolution sets the Resolution field.
func (o *ClusterNopResourceSpecProviderConfigRefPolicy) SetResolution(v *ClusterNopResourceSpecProviderConfigRefPolicyResolution) {
	o.Resolution = v
}

// GetResolve returns the Resolve field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecProviderConfigRefPolicy) GetResolve() *ClusterNopResourceSpecProviderConfigRefPolicyResolve {
	if o == nil {
		return nil
	}
	return o.Resolve
}

// SetResolve sets the Resolve field.
func (o *ClusterNopResourceSpecProviderConfigRefPolicy) SetResolve(v *ClusterNopResourceSpecProviderConfigRefPolicyResolve) {
	o.Resolve = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecProviderConfigRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *ClusterNopResourceSpecProviderConfigRef) SetName(v *string) {
	o.Name = v
}

// GetPolicy returns the Policy field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecProviderConfigRef) GetPolicy() *ClusterNopResourceSpecProviderConfigRefPolicy {
	if o == nil {
		return nil
	}
	return o.Policy
}

// SetPolicy sets the Policy field.
func (o *ClusterNopResourceSpecProviderConfigRef) SetPolicy(v *ClusterNopResourceSpecProviderConfigRefPolicy) {
	o.Policy = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecWriteConnectionSecretToRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *ClusterNopResourceSpecWriteConnectionSecretToRef) SetName(v *string) {
	o.Name = v
}

// GetNamespace returns the Namespace field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpecWriteConnectionSecretToRef) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

// SetNamespace sets the Namespace field.
func (o *ClusterNopResourceSpecWriteConnectionSecretToRef) SetNamespace(v *string) {
	o.Namespace = v
}

// GetDeletionPolicy returns the DeletionPolicy field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpec) GetDeletionPolicy() *ClusterNopResourceSpecDeletionPolicy {
	if o == nil {
		return nil
	}
	return o.DeletionPolicy
}

// SetDeletionPolicy sets the DeletionPolicy field.
func (o *ClusterNopResourceSpec) SetDeletionPolicy(v *ClusterNopResourceSpecDeletionPolicy) {
	o.DeletionPolicy = v
}

// GetForProvider returns the ForProvider field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpec) GetForProvider() *ClusterNopResourceSpecForProvider {
	if o == nil {
		return nil
	}
	return o.ForProvider
}

// SetForProvider sets the ForProvider field.
func (o *ClusterNopResourceSpec) SetForProvider(v *ClusterNopResourceSpecForProvider) {
	o.ForProvider = v
}

// GetManagementPolicies returns the ManagementPolicies field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpec) GetManagementPolicies() *[]ClusterNopResourceSpecManagementPoliciesItem {
	if o == nil {
		return nil
	}
	return o.ManagementPolicies
}

// SetManagementPolicies sets the ManagementPolicies field.
func (o *ClusterNopResourceSpec) SetManagementPolicies(v *[]ClusterNopResourceSpecManagementPoliciesItem) {
	o.ManagementPolicies = v
}

// GetProviderConfigRef returns the ProviderConfigRef field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpec) GetProviderConfigRef() *ClusterNopResourceSpecProviderConfigRef {
	if o == nil {
		return nil
	}
	return o.ProviderConfigRef
}

// SetProviderConfigRef sets the ProviderConfigRef field.
func (o *ClusterNopResourceSpec) SetProviderConfigRef(v *ClusterNopResourceSpecProviderConfigRef) {
	o.ProviderConfigRef = v
}

// GetWriteConnectionSecretToRef returns the WriteConnectionSecretToRef field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceSpec) GetWriteConnectionSecretToRef() *ClusterNopResourceSpecWriteConnectionSecretToRef {
	if o == nil {
		return nil
	}
	return o.WriteConnectionSecretToRef
}

// SetWriteConnectionSecretToRef sets the WriteConnectionSecretToRef field.
func (o *ClusterNopResourceSpec) SetWriteConnectionSecretToRef(v *ClusterNopResourceSpecWriteConnectionSecretToRef) {
	o.WriteConnectionSecretToRef = v
}

// GetFields returns the Fields field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusAtProvider) GetFields() *ClusterNopResourceStatusAtProviderFields {
	if o == nil {
		return nil
	}
	return o.Fields
}

// SetFields sets the Fields field.
func (o *ClusterNopResourceStatusAtProvider) SetFields(v *ClusterNopResourceStatusAtProviderFields) {
	o.Fields = v
}

// GetLastTransitionTime returns the LastTransitionTime field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetLastTransitionTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastTransitionTime
}

// SetLastTransitionTime sets the LastTransitionTime field.
func (o *ClusterNopResourceStatusConditionsItem) SetLastTransitionTime(v *time.Time) {
	o.LastTransitionTime = v
}

// GetMessage returns the Message field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// SetMessage sets the Message field.
func (o *ClusterNopResourceStatusConditionsItem) SetMessage(v *string) {
	o.Message = v
}

// GetObservedGeneration returns the ObservedGeneration field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetObservedGeneration() *int64 {
	if o == nil {
		return nil
	}
	return o.ObservedGeneration
}

// SetObservedGeneration sets the ObservedGeneration field.
func (o *ClusterNopResourceStatusConditionsItem) SetObservedGeneration(v *int64) {
	o.ObservedGeneration = v
}

// GetReason returns the Reason field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

// SetReason sets the Reason field.
func (o *ClusterNopResourceStatusConditionsItem) SetReason(v *string) {
	o.Reason = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *ClusterNopResourceStatusConditionsItem) SetStatus(v *string) {
	o.Status = v
}

// GetType returns the Type field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatusConditionsItem) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

// SetType sets the Type field.
func (o *ClusterNopResourceStatusConditionsItem) SetType(v *string) {
	o.Type = v
}

// GetAtProvider returns the AtProvider field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatus) GetAtProvider() *ClusterNopResourceStatusAtProvider {
	if o == nil {
		return nil
	}
	return o.AtProvider
}

// SetAtProvider sets the AtProvider field.
func (o *ClusterNopResourceStatus) SetAtProvider(v *ClusterNopResourceStatusAtProvider) {
	o.AtProvider = v
}

// GetConditions returns the Conditions field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatus) GetConditions() *[]ClusterNopResourceStatusConditionsItem {
	if o == nil {
		return nil
	}
	return o.Conditions
}

// SetConditions sets the Conditions field.
func (o *ClusterNopResourceStatus) SetConditions(v *[]ClusterNopResourceStatusConditionsItem) {
	o.Conditions = v
}

// GetObservedGeneration returns the ObservedGeneration field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceStatus) GetObservedGeneration() *int64 {
	if o == nil {
		return nil
	}
	return o.ObservedGeneration
}

// SetObservedGeneration sets the ObservedGeneration field.
func (o *ClusterNopResourceStatus) SetObservedGeneration(v *int64) {
	o.ObservedGeneration = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResource) GetAPIVersion() *ClusterNopResourceAPIVersion {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *ClusterNopResource) SetAPIVersion(v *ClusterNopResourceAPIVersion) {
	o.APIVersion = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResource) GetKind() *ClusterNopResourceKind {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *ClusterNopResource) SetKind(v *ClusterNopResourceKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResource) GetMetadata() *metav1.ObjectMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *ClusterNopResource) SetMetadata(v *metav1.ObjectMeta) {
	o.Metadata = v
}

// GetSpec returns the Spec field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResource) GetSpec() *ClusterNopResourceSpec {
	if o == nil {
		return nil
	}
	return o.Spec
}

// SetSpec sets the Spec field.
func (o *ClusterNopResource) SetSpec(v *ClusterNopResourceSpec) {
	o.Spec = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResource) GetStatus() *ClusterNopResourceStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *ClusterNopResource) SetStatus(v *ClusterNopResourceStatus) {
	o.Status = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceList) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *ClusterNopResourceList) SetAPIVersion(v *string) {
	o.APIVersion = v
}

// GetItems returns the Items field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceList) GetItems() *[]IoCrossplaneNopV1Alpha1ClusterNopResource {
	if o == nil {
		return nil
	}
	return o.Items
}

// SetItems sets the Items field.
func (o *ClusterNopResourceList) SetItems(v *[]IoCrossplaneNopV1Alpha1ClusterNopResource) {
	o.Items = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceList) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *ClusterNopResourceList) SetKind(v *string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *ClusterNopResourceList) GetMetadata() *metav1.ListMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *ClusterNopResourceList) SetMetadata(v *metav1.ListMeta) {
	o.Metadata = v
}
