// Code generated by github.com/crossplane/cli/v2 DO NOT EDIT.
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// GroupVersion is the API group and version for the types in this package.
var GroupVersion = schema.GroupVersion{Group: "nop.crossplane.io", Version: "v1alpha1"}

// SchemeBuilder collects the functions that register this package's types with
// a runtime.Scheme. Each type registers itself via an init function.
var SchemeBuilder = &runtime.SchemeBuilder{}

// AddToScheme registers this package's types with the given runtime.Scheme.
var AddToScheme = SchemeBuilder.AddToScheme
