// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.5.0-rc.0.0.20260814234830-5bace94891a5 DO NOT EDIT.
package v1alpha1

import (
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for NopResourceAPIVersion.
const (
	NopResourceAPIVersionNopCrossplaneIoV1Alpha1 NopResourceAPIVersion = "nop.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the NopResourceAPIVersion enum.
func (e NopResourceAPIVersion) Valid() bool {
	switch e {
	case NopResourceAPIVersionNopCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for NopResourceKind.
const (
	NopResourceKindNopResource NopResourceKind = "NopResource"
)

// Valid indicates whether the value is a known member of the NopResourceKind enum.
func (e NopResourceKind) Valid() bool {
	switch e {
	case NopResourceKindNopResource:
		return true
	default:
		return false
	}
}

// Defines values for NopResourceSpecDeletionPolicy.
const (
	NopResourceSpecDeletionPolicyDelete NopResourceSpecDeletionPolicy = "Delete"
	NopResourceSpecDeletionPolicyOrphan NopResourceSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the NopResourceSpecDeletionPolicy enum.
func (e NopResourceSpecDeletionPolicy) Valid() bool {
	switch e {
	case NopResourceSpecDeletionPolicyDelete:
		return true
	case NopResourceSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for NopResourceSpecManagementPoliciesItem.
const (
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItem               NopResourceSpecManagementPoliciesItem = "*"
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemCreate         NopResourceSpecManagementPoliciesItem = "Create"
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemDelete         NopResourceSpecManagementPoliciesItem = "Delete"
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemLateInitialize NopResourceSpecManagementPoliciesItem = "LateInitialize"
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemObserve        NopResourceSpecManagementPoliciesItem = "Observe"
	NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemUpdate         NopResourceSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the NopResourceSpecManagementPoliciesItem enum.
func (e NopResourceSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItem:
		return true
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemCreate:
		return true
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemDelete:
		return true
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemLateInitialize:
		return true
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemObserve:
		return true
	case NopResourceSpecManagementPoliciesItemNopResourceSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for NopResourceSpecProviderConfigRefPolicyResolution.
const (
	NopResourceSpecProviderConfigRefPolicyResolutionOptional NopResourceSpecProviderConfigRefPolicyResolution = "Optional"
	NopResourceSpecProviderConfigRefPolicyResolutionRequired NopResourceSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the NopResourceSpecProviderConfigRefPolicyResolution enum.
func (e NopResourceSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case NopResourceSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case NopResourceSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for NopResourceSpecProviderConfigRefPolicyResolve.
const (
	NopResourceSpecProviderConfigRefPolicyResolveAlways       NopResourceSpecProviderConfigRefPolicyResolve = "Always"
	NopResourceSpecProviderConfigRefPolicyResolveIfNotPresent NopResourceSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the NopResourceSpecProviderConfigRefPolicyResolve enum.
func (e NopResourceSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case NopResourceSpecProviderConfigRefPolicyResolveAlways:
		return true
	case NopResourceSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoCrossplaneNopV1Alpha1NopResource A NopResource is an example API type.
type IoCrossplaneNopV1Alpha1NopResource = NopResource

// NopResourceAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type NopResourceAPIVersion string

// NopResourceKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type NopResourceKind string

// NopResourceSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type NopResourceSpecDeletionPolicy string

// NopResourceSpecForProviderConditionAfterItem ConditionAfter specifies a condition of a NopResource that should be
// set after a certain duration.
type NopResourceSpecForProviderConditionAfterItem struct {
	// ConditionReason ConditionReason to set - e.g. Available.
	ConditionReason *string `json:"conditionReason,omitempty"`

	// ConditionStatus ConditionStatus to set - e.g. True.
	ConditionStatus *string `json:"conditionStatus,omitempty"`

	// ConditionType ConditionType to set - e.g. Ready.
	ConditionType *string `json:"conditionType,omitempty"`

	// Time Time is the duration after which the condition should be set.
	Time *string `json:"time,omitempty"`
}

// NopResourceSpecForProviderConnectionDetailsItem ConnectionDetail specifies a connection detail a NopResource should
// emit.
type NopResourceSpecForProviderConnectionDetailsItem struct {
	// Name Name of the connection detail.
	Name *string `json:"name,omitempty"`

	// Value Value of the connection detail.
	Value *string `json:"value,omitempty"`
}

// NopResourceSpecForProviderFields Fields is an arbitrary object you can patch to and from. It has no
// schema, is not validated, and is not used by the NopResource controller.
type NopResourceSpecForProviderFields = map[string]interface{}

// NopResourceSpecForProvider NopParameters are the configurable fields of a NopResource.
type NopResourceSpecForProvider struct {
	// ConditionAfter ConditionAfter can be used to set status conditions after a specified
	// time. By default, a NopResource will only have a status condition of
	// Type: Synced. It will never have a status condition of Type: Ready
	// unless one is configured here.
	ConditionAfter *[]NopResourceSpecForProviderConditionAfterItem `json:"conditionAfter,omitempty"`

	// ConnectionDetails ConnectionDetails that this NopResource should emit on each reconcile.
	ConnectionDetails *[]NopResourceSpecForProviderConnectionDetailsItem `json:"connectionDetails,omitempty"`

	// Fields Fields is an arbitrary object you can patch to and from. It has no
	// schema, is not validated, and is not used by the NopResource controller.
	Fields *NopResourceSpecForProviderFields `json:"fields,omitempty"`
}

// NopResourceSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type NopResourceSpecManagementPoliciesItem string

// NopResourceSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type NopResourceSpecProviderConfigRefPolicyResolution string

// NopResourceSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type NopResourceSpecProviderConfigRefPolicyResolve string

// NopResourceSpecProviderConfigRefPolicy Policies for referencing.
type NopResourceSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *NopResourceSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *NopResourceSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// NopResourceSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type NopResourceSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *NopResourceSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// NopResourceSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type NopResourceSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// NopResourceSpec A NopSpec defines the desired state of a NopResource.
type NopResourceSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *NopResourceSpecDeletionPolicy `json:"deletionPolicy,omitempty"`

	// ForProvider NopParameters are the configurable fields of a NopResource.
	ForProvider *NopResourceSpecForProvider `json:"forProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]NopResourceSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *NopResourceSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *NopResourceSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// NopResourceStatusAtProviderFields Fields is an arbitrary object you can patch to and from. It has no
// schema, is not validated, and is not used by the NopResource controller.
type NopResourceStatusAtProviderFields = map[string]interface{}

// NopResourceStatusAtProvider NopObservation are the observable fields of a NopResource.
type NopResourceStatusAtProvider struct {
	// Fields Fields is an arbitrary object you can patch to and from. It has no
	// schema, is not validated, and is not used by the NopResource controller.
	Fields *NopResourceStatusAtProviderFields `json:"fields,omitempty"`
}

// NopResourceStatusConditionsItem A Condition that may apply to a resource.
type NopResourceStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// NopResourceStatus A NopStatus represents the observed state of a NopResource.
type NopResourceStatus struct {
	// AtProvider NopObservation are the observable fields of a NopResource.
	AtProvider *NopResourceStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]NopResourceStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// NopResource A NopResource is an example API type.
type NopResource struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *NopResourceAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *NopResourceKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A NopSpec defines the desired state of a NopResource.
	Spec *NopResourceSpec `json:"spec,omitempty"`

	// Status A NopStatus represents the observed state of a NopResource.
	Status *NopResourceStatus `json:"status,omitempty"`
}

// IoCrossplaneNopV1Alpha1NopResourceList NopResourceList is a list of NopResource
type IoCrossplaneNopV1Alpha1NopResourceList = NopResourceList

// NopResourceList NopResourceList is a list of NopResource
type NopResourceList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of nopresources. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneNopV1Alpha1NopResource `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecForProviderConditionAfterItem) DeepCopyInto(out *NopResourceSpecForProviderConditionAfterItem) {
	*out = *in
	if in.ConditionReason != nil {
		in, out := &in.ConditionReason, &out.ConditionReason
		*out = new(string)
		**out = **in
	}
	if in.ConditionStatus != nil {
		in, out := &in.ConditionStatus, &out.ConditionStatus
		*out = new(string)
		**out = **in
	}
	if in.ConditionType != nil {
		in, out := &in.ConditionType, &out.ConditionType
		*out = new(string)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecForProviderConditionAfterItem) DeepCopy() *NopResourceSpecForProviderConditionAfterItem {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecForProviderConditionAfterItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecForProviderConnectionDetailsItem) DeepCopyInto(out *NopResourceSpecForProviderConnectionDetailsItem) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecForProviderConnectionDetailsItem) DeepCopy() *NopResourceSpecForProviderConnectionDetailsItem {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecForProviderConnectionDetailsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecForProvider) DeepCopyInto(out *NopResourceSpecForProvider) {
	*out = *in
	if in.ConditionAfter != nil {
		in, out := &in.ConditionAfter, &out.ConditionAfter
		*out = new([]NopResourceSpecForProviderConditionAfterItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]NopResourceSpecForProviderConditionAfterItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ConnectionDetails != nil {
		in, out := &in.ConnectionDetails, &out.ConnectionDetails
		*out = new([]NopResourceSpecForProviderConnectionDetailsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]NopResourceSpecForProviderConnectionDetailsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = new(NopResourceSpecForProviderFields)
		if *in != nil {
			in, out := *in, *out
			*out = make(NopResourceSpecForProviderFields, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecForProvider) DeepCopy() *NopResourceSpecForProvider {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecProviderConfigRefPolicy) DeepCopyInto(out *NopResourceSpecProviderConfigRefPolicy) {
	*out = *in
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(NopResourceSpecProviderConfigRefPolicyResolution)
		**out = **in
	}
	if in.Resolve != nil {
		in, out := &in.Resolve, &out.Resolve
		*out = new(NopResourceSpecProviderConfigRefPolicyResolve)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecProviderConfigRefPolicy) DeepCopy() *NopResourceSpecProviderConfigRefPolicy {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecProviderConfigRefPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecProviderConfigRef) DeepCopyInto(out *NopResourceSpecProviderConfigRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(NopResourceSpecProviderConfigRefPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecProviderConfigRef) DeepCopy() *NopResourceSpecProviderConfigRef {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecProviderConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpecWriteConnectionSecretToRef) DeepCopyInto(out *NopResourceSpecWriteConnectionSecretToRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpecWriteConnectionSecretToRef) DeepCopy() *NopResourceSpecWriteConnectionSecretToRef {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpecWriteConnectionSecretToRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceSpec) DeepCopyInto(out *NopResourceSpec) {
	*out = *in
	if in.DeletionPolicy != nil {
		in, out := &in.DeletionPolicy, &out.DeletionPolicy
		*out = new(NopResourceSpecDeletionPolicy)
		**out = **in
	}
	if in.ForProvider != nil {
		in, out := &in.ForProvider, &out.ForProvider
		*out = new(NopResourceSpecForProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.ManagementPolicies != nil {
		in, out := &in.ManagementPolicies, &out.ManagementPolicies
		*out = new([]NopResourceSpecManagementPoliciesItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]NopResourceSpecManagementPoliciesItem, len(*in))
			copy(*out, *in)
		}
	}
	if in.ProviderConfigRef != nil {
		in, out := &in.ProviderConfigRef, &out.ProviderConfigRef
		*out = new(NopResourceSpecProviderConfigRef)
		(*in).DeepCopyInto(*out)
	}
	if in.WriteConnectionSecretToRef != nil {
		in, out := &in.WriteConnectionSecretToRef, &out.WriteConnectionSecretToRef
		*out = new(NopResourceSpecWriteConnectionSecretToRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceSpec) DeepCopy() *NopResourceSpec {
	if in == nil {
		return nil
	}
	out := new(NopResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceStatusAtProvider) DeepCopyInto(out *NopResourceStatusAtProvider) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = new(NopResourceStatusAtProviderFields)
		if *in != nil {
			in, out := *in, *out
			*out = make(NopResourceStatusAtProviderFields, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceStatusAtProvider) DeepCopy() *NopResourceStatusAtProvider {
	if in == nil {
		return nil
	}
	out := new(NopResourceStatusAtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceStatusConditionsItem) DeepCopyInto(out *NopResourceStatusConditionsItem) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(time.Time)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceStatusConditionsItem) DeepCopy() *NopResourceStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(NopResourceStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceStatus) DeepCopyInto(out *NopResourceStatus) {
	*out = *in
	if in.AtProvider != nil {
		in, out := &in.AtProvider, &out.AtProvider
		*out = new(NopResourceStatusAtProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]NopResourceStatusConditionsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]NopResourceStatusConditionsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceStatus) DeepCopy() *NopResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NopResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *NopResource) DeepCopyInto(out *NopResource) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(NopResourceAPIVersion)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(NopResourceKind)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(NopResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(NopResourceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResource) DeepCopy() *NopResource {
	if in == nil {
		return nil
	}
	out := new(NopResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *NopResource) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *NopResource) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *NopResource) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *NopResource) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := NopResourceAPIVersion(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := NopResourceKind(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &NopResource{})
		return nil
	})
}

// DeepCopyInto copies the receiver into out.
func (in *NopResourceList) DeepCopyInto(out *NopResourceList) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new([]IoCrossplaneNopV1Alpha1NopResource)
		if *in != nil {
			in, out := *in, *out
			*out = make([]IoCrossplaneNopV1Alpha1NopResource, len(*in))
			copy(*out, *in)
		}
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ListMeta)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *NopResourceList) DeepCopy() *NopResourceList {
	if in == nil {
		return nil
	}
	out := new(NopResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *NopResourceList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *NopResourceList) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *NopResourceList) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *NopResourceList) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := string(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := string(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &NopResourceList{})
		return nil
	})
}

// GetConditionReason returns the ConditionReason field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConditionAfterItem) GetConditionReason() *string {
	if o == nil {
		return nil
	}
	return o.ConditionReason
}

// SetConditionReason sets the ConditionReason field.
func (o *NopResourceSpecForProviderConditionAfterItem) SetConditionReason(v *string) {
	o.ConditionReason = v
}

// GetConditionStatus returns the ConditionStatus field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConditionAfterItem) GetConditionStatus() *string {
	if o == nil {
		return nil
	}
	return o.ConditionStatus
}

// SetConditionStatus sets the ConditionStatus field.
func (o *NopResourceSpecForProviderConditionAfterItem) SetConditionStatus(v *string) {
	o.ConditionStatus = v
}

// GetConditionType returns the ConditionType field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConditionAfterItem) GetConditionType() *string {
	if o == nil {
		return nil
	}
	return o.ConditionType
}

// SetConditionType sets the ConditionType field.
func (o *NopResourceSpecForProviderConditionAfterItem) SetConditionType(v *string) {
	o.ConditionType = v
}

// GetTime returns the Time field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConditionAfterItem) GetTime() *string {
	if o == nil {
		return nil
	}
	return o.Time
}

// SetTime sets the Time field.
func (o *NopResourceSpecForProviderConditionAfterItem) SetTime(v *string) {
	o.Time = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConnectionDetailsItem) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *NopResourceSpecForProviderConnectionDetailsItem) SetName(v *string) {
	o.Name = v
}

// GetValue returns the Value field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProviderConnectionDetailsItem) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// SetValue sets the Value field.
func (o *NopResourceSpecForProviderConnectionDetailsItem) SetValue(v *string) {
	o.Value = v
}

// GetConditionAfter returns the ConditionAfter field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProvider) GetConditionAfter() *[]NopResourceSpecForProviderConditionAfterItem {
	if o == nil {
		return nil
	}
	return o.ConditionAfter
}

// SetConditionAfter sets the ConditionAfter field.
func (o *NopResourceSpecForProvider) SetConditionAfter(v *[]NopResourceSpecForProviderConditionAfterItem) {
	o.ConditionAfter = v
}

// GetConnectionDetails returns the ConnectionDetails field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProvider) GetConnectionDetails() *[]NopResourceSpecForProviderConnectionDetailsItem {
	if o == nil {
		return nil
	}
	return o.ConnectionDetails
}

// SetConnectionDetails sets the ConnectionDetails field.
func (o *NopResourceSpecForProvider) SetConnectionDetails(v *[]NopResourceSpecForProviderConnectionDetailsItem) {
	o.ConnectionDetails = v
}

// GetFields returns the Fields field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecForProvider) GetFields() *NopResourceSpecForProviderFields {
	if o == nil {
		return nil
	}
	return o.Fields
}

// SetFields sets the Fields field.
func (o *NopResourceSpecForProvider) SetFields(v *NopResourceSpecForProviderFields) {
	o.Fields = v
}

// GetResolution returns the Resolution field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecProviderConfigRefPolicy) GetResolution() *NopResourceSpecProviderConfigRefPolicyResolution {
	if o == nil {
		return nil
	}
	return o.Resolution
}

// SetResolution sets the Resolution field.
func (o *NopResourceSpecProviderConfigRefPolicy) SetResolution(v *NopResourceSpecProviderConfigRefPolicyResolution) {
	o.Resolution = v
}

// GetResolve returns the Resolve field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecProviderConfigRefPolicy) GetResolve() *NopResourceSpecProviderConfigRefPolicyResolve {
	if o == nil {
		return nil
	}
	return o.Resolve
}

// SetResolve sets the Resolve field.
func (o *NopResourceSpecProviderConfigRefPolicy) SetResolve(v *NopResourceSpecProviderConfigRefPolicyResolve) {
	o.Resolve = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecProviderConfigRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *NopResourceSpecProviderConfigRef) SetName(v *string) {
	o.Name = v
}

// GetPolicy returns the Policy field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecProviderConfigRef) GetPolicy() *NopResourceSpecProviderConfigRefPolicy {
	if o == nil {
		return nil
	}
	return o.Policy
}

// SetPolicy sets the Policy field.
func (o *NopResourceSpecProviderConfigRef) SetPolicy(v *NopResourceSpecProviderConfigRefPolicy) {
	o.Policy = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecWriteConnectionSecretToRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *NopResourceSpecWriteConnectionSecretToRef) SetName(v *string) {
	o.Name = v
}

// GetNamespace returns the Namespace field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpecWriteConnectionSecretToRef) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

// SetNamespace sets the Namespace field.
func (o *NopResourceSpecWriteConnectionSecretToRef) SetNamespace(v *string) {
	o.Namespace = v
}

// GetDeletionPolicy returns the DeletionPolicy field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpec) GetDeletionPolicy() *NopResourceSpecDeletionPolicy {
	if o == nil {
		return nil
	}
	return o.DeletionPolicy
}

// SetDeletionPolicy sets the DeletionPolicy field.
func (o *NopResourceSpec) SetDeletionPolicy(v *NopResourceSpecDeletionPolicy) {
	o.DeletionPolicy = v
}

// GetForProvider returns the ForProvider field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpec) GetForProvider() *NopResourceSpecForProvider {
	if o == nil {
		return nil
	}
	return o.ForProvider
}

// SetForProvider sets the ForProvider field.
func (o *NopResourceSpec) SetForProvider(v *NopResourceSpecForProvider) {
	o.ForProvider = v
}

// GetManagementPolicies returns the ManagementPolicies field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpec) GetManagementPolicies() *[]NopResourceSpecManagementPoliciesItem {
	if o == nil {
		return nil
	}
	return o.ManagementPolicies
}

// SetManagementPolicies sets the ManagementPolicies field.
func (o *NopResourceSpec) SetManagementPolicies(v *[]NopResourceSpecManagementPoliciesItem) {
	o.ManagementPolicies = v
}

// GetProviderConfigRef returns the ProviderConfigRef field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpec) GetProviderConfigRef() *NopResourceSpecProviderConfigRef {
	if o == nil {
		return nil
	}
	return o.ProviderConfigRef
}

// SetProviderConfigRef sets the ProviderConfigRef field.
func (o *NopResourceSpec) SetProviderConfigRef(v *NopResourceSpecProviderConfigRef) {
	o.ProviderConfigRef = v
}

// GetWriteConnectionSecretToRef returns the WriteConnectionSecretToRef field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceSpec) GetWriteConnectionSecretToRef() *NopResourceSpecWriteConnectionSecretToRef {
	if o == nil {
		return nil
	}
	return o.WriteConnectionSecretToRef
}

// SetWriteConnectionSecretToRef sets the WriteConnectionSecretToRef field.
func (o *NopResourceSpec) SetWriteConnectionSecretToRef(v *NopResourceSpecWriteConnectionSecretToRef) {
	o.WriteConnectionSecretToRef = v
}

// GetFields returns the Fields field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusAtProvider) GetFields() *NopResourceStatusAtProviderFields {
	if o == nil {
		return nil
	}
	return o.Fields
}

// SetFields sets the Fields field.
func (o *NopResourceStatusAtProvider) SetFields(v *NopResourceStatusAtProviderFields) {
	o.Fields = v
}

// GetLastTransitionTime returns the LastTransitionTime field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetLastTransitionTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastTransitionTime
}

// SetLastTransitionTime sets the LastTransitionTime field.
func (o *NopResourceStatusConditionsItem) SetLastTransitionTime(v *time.Time) {
	o.LastTransitionTime = v
}

// GetMessage returns the Message field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// SetMessage sets the Message field.
func (o *NopResourceStatusConditionsItem) SetMessage(v *string) {
	o.Message = v
}

// GetObservedGeneration returns the ObservedGeneration field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetObservedGeneration() *int64 {
	if o == nil {
		return nil
	}
	return o.ObservedGeneration
}

// SetObservedGeneration sets the ObservedGeneration field.
func (o *NopResourceStatusConditionsItem) SetObservedGeneration(v *int64) {
	o.ObservedGeneration = v
}

// GetReason returns the Reason field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

// SetReason sets the Reason field.
func (o *NopResourceStatusConditionsItem) SetReason(v *string) {
	o.Reason = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *NopResourceStatusConditionsItem) SetStatus(v *string) {
	o.Status = v
}

// GetType returns the Type field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatusConditionsItem) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

// SetType sets the Type field.
func (o *NopResourceStatusConditionsItem) SetType(v *string) {
	o.Type = v
}

// GetAtProvider returns the AtProvider field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatus) GetAtProvider() *NopResourceStatusAtProvider {
	if o == nil {
		return nil
	}
	return o.AtProvider
}

// SetAtProvider sets the AtProvider field.
func (o *NopResourceStatus) SetAtProvider(v *NopResourceStatusAtProvider) {
	o.AtProvider = v
}

// GetConditions returns the Conditions field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatus) GetConditions() *[]NopResourceStatusConditionsItem {
	if o == nil {
		return nil
	}
	return o.Conditions
}

// SetConditions sets the Conditions field.
func (o *NopResourceStatus) SetConditions(v *[]NopResourceStatusConditionsItem) {
	o.Conditions = v
}

// GetObservedGeneration returns the ObservedGeneration field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceStatus) GetObservedGeneration() *int64 {
	if o == nil {
		return nil
	}
	return o.ObservedGeneration
}

// SetObservedGeneration sets the ObservedGeneration field.
func (o *NopResourceStatus) SetObservedGeneration(v *int64) {
	o.ObservedGeneration = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *NopResource) GetAPIVersion() *NopResourceAPIVersion {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *NopResource) SetAPIVersion(v *NopResourceAPIVersion) {
	o.APIVersion = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *NopResource) GetKind() *NopResourceKind {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *NopResource) SetKind(v *NopResourceKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *NopResource) GetMetadata() *metav1.ObjectMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *NopResource) SetMetadata(v *metav1.ObjectMeta) {
	o.Metadata = v
}

// GetSpec returns the Spec field.
// It returns the zero value if the receiver is nil.
func (o *NopResource) GetSpec() *NopResourceSpec {
	if o == nil {
		return nil
	}
	return o.Spec
}

// SetSpec sets the Spec field.
func (o *NopResource) SetSpec(v *NopResourceSpec) {
	o.Spec = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *NopResource) GetStatus() *NopResourceStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *NopResource) SetStatus(v *NopResourceStatus) {
	o.Status = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceList) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *NopResourceList) SetAPIVersion(v *string) {
	o.APIVersion = v
}

// GetItems returns the Items field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceList) GetItems() *[]IoCrossplaneNopV1Alpha1NopResource {
	if o == nil {
		return nil
	}
	return o.Items
}

// SetItems sets the Items field.
func (o *NopResourceList) SetItems(v *[]IoCrossplaneNopV1Alpha1NopResource) {
	o.Items = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceList) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *NopResourceList) SetKind(v *string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *NopResourceList) GetMetadata() *metav1.ListMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *NopResourceList) SetMetadata(v *metav1.ListMeta) {
	o.Metadata = v
}
