// Package v1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.5.0-rc.0.0.20260814234830-5bace94891a5 DO NOT EDIT.
package v1

import (
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for XBucketsAPIVersion.
const (
	XBucketsAPIVersionExampleCrossplaneIoV1 XBucketsAPIVersion = "example.crossplane.io/v1"
)

// Valid indicates whether the value is a known member of the XBucketsAPIVersion enum.
func (e XBucketsAPIVersion) Valid() bool {
	switch e {
	case XBucketsAPIVersionExampleCrossplaneIoV1:
		return true
	default:
		return false
	}
}

// Defines values for XBucketsKind.
const (
	XBucketsKindXBuckets XBucketsKind = "XBuckets"
)

// Valid indicates whether the value is a known member of the XBucketsKind enum.
func (e XBucketsKind) Valid() bool {
	switch e {
	case XBucketsKindXBuckets:
		return true
	default:
		return false
	}
}

// Defines values for XBucketsSpecCrossplaneCompositionUpdatePolicy.
const (
	XBucketsSpecCrossplaneCompositionUpdatePolicyAutomatic XBucketsSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	XBucketsSpecCrossplaneCompositionUpdatePolicyManual    XBucketsSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the XBucketsSpecCrossplaneCompositionUpdatePolicy enum.
func (e XBucketsSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case XBucketsSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case XBucketsSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// IoCrossplaneExampleV1XBuckets XBuckets is the Schema for the XBuckets API.
type IoCrossplaneExampleV1XBuckets = XBuckets

// XBucketsAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type XBucketsAPIVersion string

// XBucketsKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type XBucketsKind string

// XBucketsSpecCrossplaneCompositionRef defines model for .
type XBucketsSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// XBucketsSpecCrossplaneCompositionRevisionRef defines model for .
type XBucketsSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// XBucketsSpecCrossplaneCompositionRevisionSelector defines model for .
type XBucketsSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// XBucketsSpecCrossplaneCompositionSelector defines model for .
type XBucketsSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// XBucketsSpecCrossplaneCompositionUpdatePolicy defines model for io.crossplane.example.v1.XBuckets.spec.crossplane.compositionUpdatePolicy.
type XBucketsSpecCrossplaneCompositionUpdatePolicy string

// XBucketsSpecCrossplaneResourceRefsItem defines model for .
type XBucketsSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// XBucketsSpecCrossplane Configures how Crossplane will reconcile this composite resource
type XBucketsSpecCrossplane struct {
	CompositionRef              *XBucketsSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *XBucketsSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *XBucketsSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *XBucketsSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *XBucketsSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]XBucketsSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// XBucketsSpec defines model for .
type XBucketsSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *XBucketsSpecCrossplane `json:"crossplane,omitempty"`
	Names      *[]string               `json:"names,omitempty"`
	Region     *string                 `json:"region,omitempty"`
}

// XBucketsStatusConditionsItem defines model for .
type XBucketsStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// XBucketsStatus defines model for .
type XBucketsStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]XBucketsStatusConditionsItem `json:"conditions,omitempty"`
}

// XBuckets XBuckets is the Schema for the XBuckets API.
type XBuckets struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *XBucketsAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *XBucketsKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec     *XBucketsSpec      `json:"spec,omitempty"`
	Status   *XBucketsStatus    `json:"status,omitempty"`
}

// IoCrossplaneExampleV1XBucketsList XBucketsList is a list of XBuckets
type IoCrossplaneExampleV1XBucketsList = XBucketsList

// XBucketsList XBucketsList is a list of XBuckets
type XBucketsList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of xbuckets. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneExampleV1XBuckets `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplaneCompositionRef) DeepCopyInto(out *XBucketsSpecCrossplaneCompositionRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplaneCompositionRef) DeepCopy() *XBucketsSpecCrossplaneCompositionRef {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplaneCompositionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplaneCompositionRevisionRef) DeepCopyInto(out *XBucketsSpecCrossplaneCompositionRevisionRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplaneCompositionRevisionRef) DeepCopy() *XBucketsSpecCrossplaneCompositionRevisionRef {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplaneCompositionRevisionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplaneCompositionRevisionSelector) DeepCopyInto(out *XBucketsSpecCrossplaneCompositionRevisionSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(map[string]string)
		if *in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplaneCompositionRevisionSelector) DeepCopy() *XBucketsSpecCrossplaneCompositionRevisionSelector {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplaneCompositionRevisionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplaneCompositionSelector) DeepCopyInto(out *XBucketsSpecCrossplaneCompositionSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(map[string]string)
		if *in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplaneCompositionSelector) DeepCopy() *XBucketsSpecCrossplaneCompositionSelector {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplaneCompositionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplaneResourceRefsItem) DeepCopyInto(out *XBucketsSpecCrossplaneResourceRefsItem) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplaneResourceRefsItem) DeepCopy() *XBucketsSpecCrossplaneResourceRefsItem {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplaneResourceRefsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpecCrossplane) DeepCopyInto(out *XBucketsSpecCrossplane) {
	*out = *in
	if in.CompositionRef != nil {
		in, out := &in.CompositionRef, &out.CompositionRef
		*out = new(XBucketsSpecCrossplaneCompositionRef)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositionRevisionRef != nil {
		in, out := &in.CompositionRevisionRef, &out.CompositionRevisionRef
		*out = new(XBucketsSpecCrossplaneCompositionRevisionRef)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositionRevisionSelector != nil {
		in, out := &in.CompositionRevisionSelector, &out.CompositionRevisionSelector
		*out = new(XBucketsSpecCrossplaneCompositionRevisionSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositionSelector != nil {
		in, out := &in.CompositionSelector, &out.CompositionSelector
		*out = new(XBucketsSpecCrossplaneCompositionSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositionUpdatePolicy != nil {
		in, out := &in.CompositionUpdatePolicy, &out.CompositionUpdatePolicy
		*out = new(XBucketsSpecCrossplaneCompositionUpdatePolicy)
		**out = **in
	}
	if in.ResourceRefs != nil {
		in, out := &in.ResourceRefs, &out.ResourceRefs
		*out = new([]XBucketsSpecCrossplaneResourceRefsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]XBucketsSpecCrossplaneResourceRefsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpecCrossplane) DeepCopy() *XBucketsSpecCrossplane {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpecCrossplane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsSpec) DeepCopyInto(out *XBucketsSpec) {
	*out = *in
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(XBucketsSpecCrossplane)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = new([]string)
		if *in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsSpec) DeepCopy() *XBucketsSpec {
	if in == nil {
		return nil
	}
	out := new(XBucketsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsStatusConditionsItem) DeepCopyInto(out *XBucketsStatusConditionsItem) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = new(time.Time)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsStatusConditionsItem) DeepCopy() *XBucketsStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(XBucketsStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsStatus) DeepCopyInto(out *XBucketsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]XBucketsStatusConditionsItem)
		if *in != nil {
			in, out := *in, *out
			*out = make([]XBucketsStatusConditionsItem, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsStatus) DeepCopy() *XBucketsStatus {
	if in == nil {
		return nil
	}
	out := new(XBucketsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *XBuckets) DeepCopyInto(out *XBuckets) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(XBucketsAPIVersion)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(XBucketsKind)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(XBucketsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(XBucketsStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBuckets) DeepCopy() *XBuckets {
	if in == nil {
		return nil
	}
	out := new(XBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *XBuckets) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *XBuckets) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *XBuckets) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *XBuckets) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := XBucketsAPIVersion(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := XBucketsKind(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &XBuckets{})
		return nil
	})
}

// DeepCopyInto copies the receiver into out.
func (in *XBucketsList) DeepCopyInto(out *XBucketsList) {
	*out = *in
	if in.APIVersion != nil {
		in, out := &in.APIVersion, &out.APIVersion
		*out = new(string)
		**out = **in
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = new([]IoCrossplaneExampleV1XBuckets)
		if *in != nil {
			in, out := *in, *out
			*out = make([]IoCrossplaneExampleV1XBuckets, len(*in))
			copy(*out, *in)
		}
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ListMeta)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *XBucketsList) DeepCopy() *XBucketsList {
	if in == nil {
		return nil
	}
	out := new(XBucketsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy of the receiver as a runtime.Object.
func (in *XBucketsList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// GetObjectKind implements runtime.Object.
func (in *XBucketsList) GetObjectKind() schema.ObjectKind { return in }

// GroupVersionKind implements schema.ObjectKind.
func (in *XBucketsList) GroupVersionKind() schema.GroupVersionKind {
	var apiVersion, kind string
	if in.APIVersion != nil {
		apiVersion = string(*in.APIVersion)
	}
	if in.Kind != nil {
		kind = string(*in.Kind)
	}
	return schema.FromAPIVersionAndKind(apiVersion, kind)
}

// SetGroupVersionKind implements schema.ObjectKind.
func (in *XBucketsList) SetGroupVersionKind(gvk schema.GroupVersionKind) {
	apiVersion := string(gvk.GroupVersion().String())
	in.APIVersion = &apiVersion
	kind := string(gvk.Kind)
	in.Kind = &kind
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &XBucketsList{})
		return nil
	})
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneCompositionRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *XBucketsSpecCrossplaneCompositionRef) SetName(v *string) {
	o.Name = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneCompositionRevisionRef) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *XBucketsSpecCrossplaneCompositionRevisionRef) SetName(v *string) {
	o.Name = v
}

// GetMatchLabels returns the MatchLabels field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneCompositionRevisionSelector) GetMatchLabels() *map[string]string {
	if o == nil {
		return nil
	}
	return o.MatchLabels
}

// SetMatchLabels sets the MatchLabels field.
func (o *XBucketsSpecCrossplaneCompositionRevisionSelector) SetMatchLabels(v *map[string]string) {
	o.MatchLabels = v
}

// GetMatchLabels returns the MatchLabels field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneCompositionSelector) GetMatchLabels() *map[string]string {
	if o == nil {
		return nil
	}
	return o.MatchLabels
}

// SetMatchLabels sets the MatchLabels field.
func (o *XBucketsSpecCrossplaneCompositionSelector) SetMatchLabels(v *map[string]string) {
	o.MatchLabels = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneResourceRefsItem) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *XBucketsSpecCrossplaneResourceRefsItem) SetAPIVersion(v *string) {
	o.APIVersion = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneResourceRefsItem) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *XBucketsSpecCrossplaneResourceRefsItem) SetKind(v *string) {
	o.Kind = v
}

// GetName returns the Name field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplaneResourceRefsItem) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// SetName sets the Name field.
func (o *XBucketsSpecCrossplaneResourceRefsItem) SetName(v *string) {
	o.Name = v
}

// GetCompositionRef returns the CompositionRef field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetCompositionRef() *XBucketsSpecCrossplaneCompositionRef {
	if o == nil {
		return nil
	}
	return o.CompositionRef
}

// SetCompositionRef sets the CompositionRef field.
func (o *XBucketsSpecCrossplane) SetCompositionRef(v *XBucketsSpecCrossplaneCompositionRef) {
	o.CompositionRef = v
}

// GetCompositionRevisionRef returns the CompositionRevisionRef field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetCompositionRevisionRef() *XBucketsSpecCrossplaneCompositionRevisionRef {
	if o == nil {
		return nil
	}
	return o.CompositionRevisionRef
}

// SetCompositionRevisionRef sets the CompositionRevisionRef field.
func (o *XBucketsSpecCrossplane) SetCompositionRevisionRef(v *XBucketsSpecCrossplaneCompositionRevisionRef) {
	o.CompositionRevisionRef = v
}

// GetCompositionRevisionSelector returns the CompositionRevisionSelector field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetCompositionRevisionSelector() *XBucketsSpecCrossplaneCompositionRevisionSelector {
	if o == nil {
		return nil
	}
	return o.CompositionRevisionSelector
}

// SetCompositionRevisionSelector sets the CompositionRevisionSelector field.
func (o *XBucketsSpecCrossplane) SetCompositionRevisionSelector(v *XBucketsSpecCrossplaneCompositionRevisionSelector) {
	o.CompositionRevisionSelector = v
}

// GetCompositionSelector returns the CompositionSelector field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetCompositionSelector() *XBucketsSpecCrossplaneCompositionSelector {
	if o == nil {
		return nil
	}
	return o.CompositionSelector
}

// SetCompositionSelector sets the CompositionSelector field.
func (o *XBucketsSpecCrossplane) SetCompositionSelector(v *XBucketsSpecCrossplaneCompositionSelector) {
	o.CompositionSelector = v
}

// GetCompositionUpdatePolicy returns the CompositionUpdatePolicy field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetCompositionUpdatePolicy() *XBucketsSpecCrossplaneCompositionUpdatePolicy {
	if o == nil {
		return nil
	}
	return o.CompositionUpdatePolicy
}

// SetCompositionUpdatePolicy sets the CompositionUpdatePolicy field.
func (o *XBucketsSpecCrossplane) SetCompositionUpdatePolicy(v *XBucketsSpecCrossplaneCompositionUpdatePolicy) {
	o.CompositionUpdatePolicy = v
}

// GetResourceRefs returns the ResourceRefs field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpecCrossplane) GetResourceRefs() *[]XBucketsSpecCrossplaneResourceRefsItem {
	if o == nil {
		return nil
	}
	return o.ResourceRefs
}

// SetResourceRefs sets the ResourceRefs field.
func (o *XBucketsSpecCrossplane) SetResourceRefs(v *[]XBucketsSpecCrossplaneResourceRefsItem) {
	o.ResourceRefs = v
}

// GetCrossplane returns the Crossplane field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpec) GetCrossplane() *XBucketsSpecCrossplane {
	if o == nil {
		return nil
	}
	return o.Crossplane
}

// SetCrossplane sets the Crossplane field.
func (o *XBucketsSpec) SetCrossplane(v *XBucketsSpecCrossplane) {
	o.Crossplane = v
}

// GetNames returns the Names field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpec) GetNames() *[]string {
	if o == nil {
		return nil
	}
	return o.Names
}

// SetNames sets the Names field.
func (o *XBucketsSpec) SetNames(v *[]string) {
	o.Names = v
}

// GetRegion returns the Region field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsSpec) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

// SetRegion sets the Region field.
func (o *XBucketsSpec) SetRegion(v *string) {
	o.Region = v
}

// GetLastTransitionTime returns the LastTransitionTime field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetLastTransitionTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastTransitionTime
}

// SetLastTransitionTime sets the LastTransitionTime field.
func (o *XBucketsStatusConditionsItem) SetLastTransitionTime(v *time.Time) {
	o.LastTransitionTime = v
}

// GetMessage returns the Message field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

// SetMessage sets the Message field.
func (o *XBucketsStatusConditionsItem) SetMessage(v *string) {
	o.Message = v
}

// GetObservedGeneration returns the ObservedGeneration field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetObservedGeneration() *int64 {
	if o == nil {
		return nil
	}
	return o.ObservedGeneration
}

// SetObservedGeneration sets the ObservedGeneration field.
func (o *XBucketsStatusConditionsItem) SetObservedGeneration(v *int64) {
	o.ObservedGeneration = v
}

// GetReason returns the Reason field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}

// SetReason sets the Reason field.
func (o *XBucketsStatusConditionsItem) SetReason(v *string) {
	o.Reason = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *XBucketsStatusConditionsItem) SetStatus(v *string) {
	o.Status = v
}

// GetType returns the Type field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatusConditionsItem) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

// SetType sets the Type field.
func (o *XBucketsStatusConditionsItem) SetType(v *string) {
	o.Type = v
}

// GetConditions returns the Conditions field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsStatus) GetConditions() *[]XBucketsStatusConditionsItem {
	if o == nil {
		return nil
	}
	return o.Conditions
}

// SetConditions sets the Conditions field.
func (o *XBucketsStatus) SetConditions(v *[]XBucketsStatusConditionsItem) {
	o.Conditions = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *XBuckets) GetAPIVersion() *XBucketsAPIVersion {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *XBuckets) SetAPIVersion(v *XBucketsAPIVersion) {
	o.APIVersion = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *XBuckets) GetKind() *XBucketsKind {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *XBuckets) SetKind(v *XBucketsKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *XBuckets) GetMetadata() *metav1.ObjectMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *XBuckets) SetMetadata(v *metav1.ObjectMeta) {
	o.Metadata = v
}

// GetSpec returns the Spec field.
// It returns the zero value if the receiver is nil.
func (o *XBuckets) GetSpec() *XBucketsSpec {
	if o == nil {
		return nil
	}
	return o.Spec
}

// SetSpec sets the Spec field.
func (o *XBuckets) SetSpec(v *XBucketsSpec) {
	o.Spec = v
}

// GetStatus returns the Status field.
// It returns the zero value if the receiver is nil.
func (o *XBuckets) GetStatus() *XBucketsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

// SetStatus sets the Status field.
func (o *XBuckets) SetStatus(v *XBucketsStatus) {
	o.Status = v
}

// GetAPIVersion returns the APIVersion field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsList) GetAPIVersion() *string {
	if o == nil {
		return nil
	}
	return o.APIVersion
}

// SetAPIVersion sets the APIVersion field.
func (o *XBucketsList) SetAPIVersion(v *string) {
	o.APIVersion = v
}

// GetItems returns the Items field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsList) GetItems() *[]IoCrossplaneExampleV1XBuckets {
	if o == nil {
		return nil
	}
	return o.Items
}

// SetItems sets the Items field.
func (o *XBucketsList) SetItems(v *[]IoCrossplaneExampleV1XBuckets) {
	o.Items = v
}

// GetKind returns the Kind field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsList) GetKind() *string {
	if o == nil {
		return nil
	}
	return o.Kind
}

// SetKind sets the Kind field.
func (o *XBucketsList) SetKind(v *string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field.
// It returns the zero value if the receiver is nil.
func (o *XBucketsList) GetMetadata() *metav1.ListMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}

// SetMetadata sets the Metadata field.
func (o *XBucketsList) SetMetadata(v *metav1.ListMeta) {
	o.Metadata = v
}
